### ISSUE TITLE
bin/www is missing

### ISSUE THREAD

**Issue by JamieMason** [hsbalar/electron-with-express#1]
Thanks a lot for making this, I'm trying it out but am having some trouble.

I have set up an mLab database and followed the instructions in the README to update `server/config/config.js`.

1) Running `node start-electron.js` results in a blank, white page in Electron.
2) Running `npm start` results in the following error;

```
[nodemon] starting `node bin/www main.js`
module.js:457
    throw err;
    ^

Error: Cannot find module '/Users/foldleft/Development/electron-with-express/bin/www'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Thanks,

Jamie

**Comment by hsbalar** [comment]
Ohh I forgot to push.
Thanks for mentioning I have added `bin/www` can check.

& thanks for refering repository **JamieMason**.
